version: '3'

services:
  ui:
    container_name: Keus_Landing_Page
    build: ./
    volumes:
      - ./:/app/frontend
    ports:
      - 5000:5000
    command: npm run dev -- --host 0.0.0.0 --port 5000